### ISSUE TITLE
No Wallpapers available 

### ISSUE THREAD

**Issue by Fede2782** [saitamasahil/Pixel-Launcher-Extended#21]
When I try to open the wallpaper picker the phone shows me only three wallpapers sections. I don't have nature, art, etc. Do you have some idea why?

**Comment by saitamasahil** [comment]
It depends upon your rom.. Report it to your rom's maintainer to add wallpapers ny Google in your rom.

**Comment by Fede2782** [comment]
Should I add the GoogleWallpaperPicker apk?
