### ISSUE TITLE
Icon pack

### ISSUE THREAD

**Issue by Gotty91** [saitamasahil/Pixel-Launcher-Extended#27]
Android 13 stock patch gen (pixel 6)
When I set an Icon pack different from that of default if i open an app and then exit with lateral swipe the system replace the Icon image of the package with the default image and then recharge the Icon pack.
Thanks.

**Comment by saitamasahil** [comment]
It will be fixed with 1.5 stable update.

**Comment by Gotty91** [comment]
You are the best, thanks
