### ISSUE TITLE
Multitasking and gestures and other things do not work

### ISSUE THREAD

**Issue by Slushi-Github** [saitamasahil/Pixel-Launcher-Extended#35]
I installed it yesterday, and since then I can not use multitasking because it crashes the launcher.
And if I disable (or uninstall) the module, the Pixel Launcher disappears.
How do I recover the original launcher? Or at least how to solve this problem
Pixel Experience - Android 13 - February update - Redmi Note 9S

**Comment by saitamasahil** [comment]
I think some other module is conflicting. I'm on PE February security patch too. It's working fine.
To uninstall PLE, Open magisk and click uninstall (don't disable). Then reboot device. If you're having trouble getting original launcher back after performing above steps then open any root file explorer & go to data/system/package_cache and delete package cache folder. Reboot device. It will fix issues.

**Comment by Slushi-Github** [comment]
Nope, even if I uninstalled it and even deactivated all the modules I had, I still have the failures I mentioned.
What's the name of that folder you said would be in data/system/package_cache?

**Comment by saitamasahil** [comment]
attach screenshot of your modules section

**Comment by Slushi-Github** [comment]
![Screenshot_20230322-173731_Magisk](https://user-images.githubusercontent.com/81278332/227044288-72f84007-54e2-4907-b4f4-9c98ab21daaa.png)

**Comment by Slushi-Github** [comment]
OHHH, It was just uninstalling all the updates contained in the Pixel Launcher and that was it.
Everything works now
I would still like to fix those bugs at some point.
