### ISSUE TITLE
Image selection buggy

### ISSUE THREAD

**Issue by K-plus69** [saitamasahil/Pixel-Launcher-Extended#37]
Hello,
Thanks for the really nice implementation of the pixel launcher first off!
I encountered 1 bug: when I'm in the recents menu, the images aren't recognized. I have to select and deselect the "select" button and then the images and links are shown.

**Comment by saitamasahil** [comment]
try flashing at a glance enhancer from add-ons section.

**Comment by K-plus69** [comment]
> try flashing at a glance enhancer from add-ons section.

Doesn't work. After flashing system intelligence stopped working and the at a glance didn't work. And the images and links in the recents still didn't get shown.

If I select and deselect the "select" button in the recents activity it immediately shows all Pictures on the app

**Comment by saitamasahil** [comment]
This bug is due to ur custom rom.
