### ISSUE TITLE
PLE not work due to wrong version judgement

### ISSUE THREAD

**Issue by closer233** [saitamasahil/Pixel-Launcher-Extended#40]
![屏幕截图 2023-04-08 211346](https://user-images.githubusercontent.com/56725325/230723133-76f4c390-fb5c-4228-b6bd-0a1ccb4dd10b.png)
Some roms(like sony stock) have newer security patch but not on android 13 qpr,that will make pixel launcher extended not working.
Worked well after exchage 202211 and 202302 in setup.sh

**Comment by saitamasahil** [comment]
PLE is not meant to use on stock roms except Google pixel stock rom and custom roms
