### ISSUE TITLE
Settings Search Doesn't Work and Causes Settings to Crash

### ISSUE THREAD

**Issue by KuroHaze** [saitamasahil/Pixel-Launcher-Extended#41]
When using the app drawer search and attempting to use shortcuts that appear under settings tapping on the shortcuts does not take you to the desired selection.  It will instead crash settings and force close the launcher if you continue tapping.  I have enclosed a video for clarity and logs are posted.  Intended behavior is for the launcher to open up the searched shortcut under settings.  Device is Pixel 7 Pro on March stable.  

**Log Cat**
https://drive.google.com/file/d/1jWJkEYoimbAZa-pd_Y6DQxF5B2yl34Sp/view?usp=sharing

**Recording**
https://user-images.githubusercontent.com/93853893/230743297-305492ee-78a8-4fce-9111-0ee9263007e7.mp4

**LSPosed Log**
[LSPosed_2023-04-08T14_34_09.883997.zip](https://github.com/saitamasahil/Pixel-Launcher-Extended/files/11184268/LSPosed_2023-04-08T14_34_09.883997.zip)

**Comment by sledgehammer0019** [comment]
I also encountered that issue on my Redmi Note 9 (merlinx) running LineageOS 20 ROM. The reason for that is because you probably enabled "developer options" while flashing the launcher. I replicated the bug and after disabling the "dev options" while flashing, I didn't encounter the bug again.

**Comment by saitamasahil** [comment]
Disable developer options
