### ISSUE TITLE
Overlay causing issues on some OEMs

### ISSUE THREAD

**Issue by duramato** [saitamasahil/Pixel-Launcher-Extended#44]
OxygenOS 13
Pixel Laucher Extented V1.5

When I try to install the module the recents page stops working and it randomly bootlooks.

I think I found the issue, which I've encoutered on other magisk modules.
It is writting the overlay to `/system/product/overlay/`, but for some reason that does not work in OxygenOS 13 and should be written to `/system/vendor/overlay/` instead. 

Some modules, like QuickSwitch have fixed this by also writting overlays to `/system/vendor/overlay/`.  https://github.com/skittles9823/QuickSwitch/commit/9c872352793c579329b171b87689d9e44cf8e25c
It seems, from QuickSwitch's source that differente device vendors handle overlays differently. Might be needed to implement some check like this: https://github.com/skittles9823/QuickSwitch/blob/master/quickswitch#L134-L193 

Examples from othermagisk module where I've had this issue and was fixed: 
https://github.com/KieronQuinn/AmbientMusicMod/issues/51
https://github.com/Kingsman44/Pixelify/issues/109

**Comment by duramato** [comment]
I've manually edited the module, which seems to have worked now.

The files i've structured like so:
```
├───addon
│   └───Volume-Key-Selector
│       └───tools
│           ├───arm
│           └───x86
├───META-INF
│   └───com
│       └───google
│           └───android
└───system
    ├───etc
    │   └───permissions
    ├───priv-app
    │   ├───QuickAccessWallet
    │   └───WallpaperPickerGoogleRelease
    ├───product
    │   ├───app
    │   │   ├───PixelThemesStub2022_and_newer
    │   │   └───ThemesStub
    │   ├───etc
    │   │   ├───default-permissions
    │   │   ├───permissions
    │   │   └───sysconfig
    │   └───priv-app
    │       ├───ExtendedSettings
    │       ├───IconShapeChanger
    │       ├───NexusLauncherRelease
    │       ├───PixelLauncherDT2S
    │       └───PixelLauncherMods
    │           └───lib
    │               └───arm64
    └───vendor
        └───overlay
            ├───PixelLauncherModsOverlay
            ├───PixelRecentsProvider
            └───ThemedIconsOverlay
```

I've also edited the setup.sh accordingly: https://gist.github.com/duramato/6df935c66caeb70fd81c975a7a92f28f

**Comment by saitamasahil** [comment]
PLE is meant to use in aosp based custom roms and Google pixel stock rom. I tried making it for oxygen OS using the above solution u provided but it doesn't work properly on all OnePlus devices.
