### ISSUE TITLE
I enabled hide clock on statusbar, but now on disabling it my clock isn't coming back

### ISSUE THREAD

**Issue by desdemona2** [saitamasahil/Pixel-Launcher-Extended#46]
I am running *pixel experience 13 April build*. 

I enabled hide clock on statusbar when pixel launcher is active. But turned out clock was invisible for all the other apps too. So i turned off the toggle but my clock isn't coming back. I tried resetting pixel mods app but things are still same.

**I removed this module from magisk, reinstalled it but still nothing is changing.**

Is there a way i can get it working again.

**Comment by saitamasahil** [comment]
Read troubleshooting section to fix this issue
