### ISSUE TITLE
 Enable Discussion Feature for Enhanced Collaboration and Issue Tracking

### ISSUE THREAD

**Issue by V3rB0se** [saitamasahil/Pixel-Launcher-Extended#53]
I wanted to discuss something regarding the repository that you've created. Currently, whenever we encounter an issue or have a question, we need to create a new issue each time. This process can be a bit cumbersome and makes it difficult for us to have meaningful discussions. I wanted to suggest enabling the discussion feature for the repository. It provides a more organized and collaborative space for addressing questions, sharing ideas, and resolving problems.

**Comment by saitamasahil** [comment]
Done. Thanks for suggestions.
