### ISSUE TITLE
Pixel Launcher Gone

### ISSUE THREAD

**Issue by jacobchins** [saitamasahil/Pixel-Launcher-Extended#64]
Hello,

I installed the module on my Pixel Fold. The taskbar does not work properly and is forced open at all times, so I uninstalled the module via Magisk, and now I don't have a Pixel Launcher at all, it's just gone. Due to the inner display home bar being tied to the Pixel Launcher, I now cannot use my home gesture at all. Any tips?

**Comment by BROKEN81** [comment]
You're going to have to reflash your firmware
